language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  apt: true
  directories:
    - ./vendor

before_script:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer dump-autoload

script:
  - phpunit
